@startuml diagrama

class Usuario {
  +APP:USER
  +id: int
  +nombre: string
  +comercio: Comercio
  
}

class Comercio{
  +APP:RESTAURANT
  +id: int
  +nombre: string
  +mesas: List<Mesa>
  +carta: Carta

  +crearMesa(numero: int): Mesa
  +crearCarta(): Carta
  +generarQR(cantMesas:int) 
}

class Mesa{
  +APP:RESTAURANT
  +id: int
  +qrCode: string


}

class Carta{
  +APP:MENU
  +id: int
  +items: List<ItemCarta>

  +agregarItem(item: ItemCarta): void
}

class ItemCarta{
  +APP:MENU
  +id: int
  +nombre: string
  +precio: double
}

class Consumidor{
  +APP:CLIENT
  +id: int
  +nombre: string

  +realizarPedido(mesa: Mesa, items: List<ItemCarta>): Pedido
}

class Pedido{
  +APP:ORDER
  +id: int
  +items: List<ItemCArta>
  +montoTotal: double
  +hora : Date
  +estado: string

  +confirmarPedido(): void
  +cancelarPedido(): void
  +pagarPedido(): Ticket
}

class SistemaPago{
  +APP:PAYMENTS

  +realizarPago(pedido: Pedido): Ticket

}

class Ticket{
  +APP:PAYMENTS
  +id: int
  +detalle: string
  +monto: double
  +fecha: Date
}

Usuario -- Comercio
Comercio -- Mesa
Comercio -- Carta
Carta -- ItemCarta
Consumidor -- Pedido
Pedido -- ItemCarta
Pedido -- SistemaPago
SistemaPago -- Ticket

@enduml